INSERT OR IGNORE INTO categories (name, description) VALUES ('General Knowledge', 'Questions about general knowledge and trivia');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Science', 'Scientific concepts, discoveries, and principles');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Mathematics & Logic', 'Mathematical problems and logical reasoning');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Technology & Computing', 'Technology, programming, and computing topics');
INSERT OR IGNORE INTO categories (name, description) VALUES ('History', 'Historical events, figures, and periods');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Geography', 'Places, maps, and geographical features');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Culture & Society', 'Cultural topics and social issues');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Literature & Language', 'Books, authors, and language topics');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Arts & Entertainment', 'Visual arts, music, movies, and entertainment');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Sports & Games', 'Sports, games, and competitive activities');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Business & Economics', 'Business principles and economic concepts');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Politics & Governance', 'Political systems and governance');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Philosophy & Psychology', 'Philosophical ideas and psychological concepts');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Health & Medicine', 'Health, wellness, and medical topics');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Nature & Environment', 'Natural world and environmental topics');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Food & Culinary', 'Cooking, cuisine, and food culture');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Religion & Mythology', 'Religious beliefs and mythological stories');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Pop Culture', 'Current trends and popular culture');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Education & Careers', 'Educational topics and career development');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Automotive & Transportation', 'Vehicles and transportation systems');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Home & Lifestyle', 'Home improvement and lifestyle topics');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Mythos & Fictional Universes', 'Fictional worlds and characters');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Ethics & Law', 'Ethical principles and legal topics');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Personal Development', 'Self-improvement and personal growth');
INSERT OR IGNORE INTO categories (name, description) VALUES ('Special Topics / Custom', 'Custom or specialized topics');
INSERT OR IGNORE INTO tags (name) VALUES ('beginner');
INSERT OR IGNORE INTO tags (name) VALUES ('intermediate');
INSERT OR IGNORE INTO tags (name) VALUES ('advanced');
INSERT OR IGNORE INTO tags (name) VALUES ('trivia');
INSERT OR IGNORE INTO tags (name) VALUES ('educational');
INSERT OR IGNORE INTO tags (name) VALUES ('fun');
INSERT OR IGNORE INTO tags (name) VALUES ('competitive');
INSERT OR IGNORE INTO tags (name) VALUES ('practice');
INSERT OR IGNORE INTO tags (name) VALUES ('certification');
INSERT OR IGNORE INTO tags (name) VALUES ('quick');
